FROM node:16-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM node:16-alpine
WORKDIR /app
ENV NODE_ENV=prod
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist
ENTRYPOINT [ "node" ]
CMD [ "dist/main.js" ]